[package]
name = "fnstack"
version = "0.1.0"
authors = ["torkleyy <torkleyy@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.1.1"

[[bench]]
name = "benches"
harness = false
